/**
 * @description       : Utility List Wrapper (Tested by Student_wrapper_Test class)
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-12-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-11-2020   f.ruggieri89@gmail.com   Initial Version
**/
public with sharing class GenericDataWrapper {
    
    /*
     * Necessary to handle with visualforce components and wrappers like Student_wrapper
     */
    public List<Student_wrapper> studentData;
    
}