/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-10-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-10-2020   f.ruggieri89@gmail.com   Initial Version
**/
public with sharing class Student_wrapper {
    
    public String ext_id {get; set;}
    public String sf_id  {get; set;}
    public String name   {get; set;}
    public String type   {get; set;}
}
